on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Vet 
      run: go vet ./...
    - name: Staticcheck
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...
    - name: Format
      run: diff -u <(echo -n) <(gofmt -d .)
